### ISSUE TITLE
"Field list is empty" when only using @GraphQLField via deriveContextObjectType

### ISSUE THREAD

**Issue by tekacs** [sangria-graphql/sangria#172]
Example:

``` scala
trait Query {
  val db: Our.Db
  import db._

  @GraphQLField
  def allUsers: Seq[User] = db.run(quote(query[User]))
}

object Query {
  case class Ctx(query: Query)
  implicit val UserOutType = deriveObjectType[Ctx, User]()
  implicit val queryType = deriveContextObjectType[Ctx, Query, Unit](_.query)
  val schema = Schema(queryType)
}
```

This works just fine if I use:

``` scala
implicit val queryType =
  deriveContextObjectType[Ctx, Query, Unit](_.query, IncludeMethods("allUsers"))
```

I've tried reading over the macro a time or two but the cause doesn't jump out at me.

Any ideas?

**Comment by tekacs** [comment]
As a weird aside - if I use `IncludeMethods`, then remove it and let the Play framework recompile it incrementally, Sangria doesn't seem to notice that it's now gone and keeps working... until I recompile from scratch. 👀

**Comment by OlegIlyenko** [comment]
Yesterday I myself faced precisely the same issue :) I tried to investigate it and debugged the macro... Turns out that in some cases scala API does not return the list of annotations at all - it's just empty, even if I have annotations on the field or method. I tried different things and nothing seem to work. Then I moved the classes (without any modifications) to a different package and suddenly scala API started to return the correct lust of annotations :upside_down_face: 

I still a bit confused with this behavior. I can try to report it (at the end of the day, scala macros are still experimental). I can also try to use java annotations instead of scala's `StaticAnnotation` which sangria uses now. I will continue investigating this.

**Comment by tekacs** [comment]
Thanks for looking into this - I've experienced similar bizarro issues with Scala macros before (I'll see if I can dig up any resolution or comments from others that I found).

I wonder if any other macro-heavy library authors would know about this bug and perhaps be aware of an existing report or a mitigation - shapeless or Quill, perhaps?

**Comment by OlegIlyenko** [comment]
Thanks for the hint! I think it would be good idea to ask for advice in other communities that also heavily use macros.

> As many other things as there might be that need fixing with scala.meta, at least it should be guaranteed to return an exact parse of the source code at all times, for things like annotations!

Indeed there are quite a few issues with macros where the results sometimes differ based on a compilation order :( I hope scala.meta will address these issues

**Comment by tekacs** [comment]
This is my mitigation, for anyone who comes across this issue before a solution is found - this simply includes all methods on a class for derivation automatically, with explicit excludes, rather than only those marked by @GraphQLField.

https://gist.github.com/tekacs/78c2ee6fff12773dcc69d004a9d6fcf2

**Comment by OlegIlyenko** [comment]
In the latest version, i think I found the root cause of this issue. As I migrated to scala 2.12, this issue became more reproducible. Turns out that annotations are also provided in a case class constructor (and in scala 2.12 it's actually the only place where one can discover them). I you suggest you to update to thi version:

https://github.com/sangria-graphql/sangria/releases/tag/v1.0.0-RC3

Meanwhile I will close this issue, since I would consider it to be resolve. but please feel free to reopen it if you face the same issue with the new version.

**Comment by tekacs** [comment]
In my own workaround code I wasn't running into this issue and was wondering why - I was accessing the case class constructor and hadn't noticed that Sangria wasn't. :smile:

I'll update and see how it goes, but given that annotations were reliable this way for me, I'm hopeful! Thanks!

**Comment by pahomovda** [comment]
Issue is still presents in 1.0.0-RC4

I have folowing setup

```scala
case class Ctx(...) extends Query with Mutation {
  ...
}

trait Query extends UserQuery { this:  Ctx =>
}

trait UserQuery { this:  Ctx with Query  =>
  
  @GraphQLField
  def users(...) = ...
}
```

When i use `implicit val queryType = deriveContextObjectType[Ctx, Query, Unit](identity)` i get 'Field list is empty'

The only way I can get of this error is using `IncludeMethods("users")`

**Comment by OlegIlyenko** [comment]
@pahomovda which scala version are you using? If it's 2.11, it would be great if you can verify it with 2.12 as well.

**Comment by pahomovda** [comment]
@OlegIlyenko I am using scala 2.11, because play 2.5 doesnt support scala 2.12 for now as I know. I will try to move it to another project with scala 2.12, but if it will work with play 2.5 it would be great.

**Comment by OlegIlyenko** [comment]
I see. I noticed that for this particular issue 2.12 has very different behavior. To begin with, I could reproduce it very reliably. RC3 fixed the annotation discovery, but I myself still experienced flackyness with 2.11 (our backend is stuck on 2.11 as well).

**Comment by astorije** [comment]
I am running into this issue as well, using Sangria 1.0.0 and Scala 2.12.1:

```sh
$ sbt compile
[info] Set current project to accounts (in build file:[...]/accounts/backend/)
[info] Compiling 2 Scala sources to [...]/accounts/backend/target/scala-2.12/classes...
[error] [...]/accounts/backend/backend.scala:99: Field list is empty
[error]   val MutationType = deriveContextObjectType[AccountRepo, AccountRepo, Unit](identity)
[error]                                                                             ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed Mar 6, 2017 12:30:36 AM
```

(Yeah, I know, `deriveContextObjectType[AccountRepo, AccountRepo, ...]` is probably not ideal, but I'm still very new to all the things involved here and I'm still trying to figure this out 😅)

Same as OP, it used to work fine, then started to see this after I rebuilt from scratch and now it won't compile.
It's still hard for me to say if this is a bug on my end or not, so [here](https://github.com/astorije/accounts/blob/8c29a43948fd78b67f4ff7007bfeedbfbfc4dbc9/backend/backend.scala#L99) is the exact code at this exact commit where I'm noticing this issue.

**Comment by OlegIlyenko** [comment]
@astorije Thanks a lot for sharing this info! This is quite puzzling, macro behave in a quite unpredictable way when it comes to annotation discovery. I though that scala 2.12 is improved in this respect, but turns out that there are still some issues. I need investigate it further.

**Comment by pahomovda** [comment]
interesting fact: 
looks like annotation with parameters like `@GraphQLTags(...)` is never missed.

**Comment by marioduarte** [comment]
Unfortunately this issue is still there with Scala 2.12.4 and Sangria 1.3.2 😞

**Comment by milanvdmria** [comment]
Same here. Scala 2.12.4, sbt 1.0.3, and sangria 1.3.2

**Comment by OlegIlyenko** [comment]
Looks like #317 has a solution for this issue. Let's hope it will solve all of the edge-cases. If not, please feel free to reopen/comment on this issue (or create a new one) to narrow down the remaining edge-cases.
