### ISSUE TITLE
v3.0.0-RC7 breaks Sangria slowlog

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#812]
[Sangria slowlog](https://github.com/sangria-graphql/sangria-slowlog) is broken with https://github.com/sangria-graphql/sangria/releases/tag/v3.0.0-RC6

```
java.lang.NoSuchMethodError: 'java.lang.String sangria.ast.Document.renderPretty()'
	at sangria.slowlog.QueryMetrics.extension(QueryMetrics.scala:328)
	at sangria.slowlog.SlowLog.afterQueryExtensions(SlowLog.scala:56)
	at sangria.slowlog.SlowLog.afterQueryExtensions(SlowLog.scala:15)
	at sangria.execution.Resolver.$anonfun$marshallExtensions$1(Resolver.scala:178)
	at scala.collection.immutable.List.flatMap(List.scala:293)
```

**Comment by yanns** [comment]
Broken by https://github.com/sangria-graphql/sangria/pull/777

**Comment by yanns** [comment]
Fixed by https://github.com/sangria-graphql/sangria-slowlog/releases/tag/v2.0.4
