### ISSUE TITLE
Binary compatibility broken in v4.2.16

### ISSUE THREAD

**Issue by kyri-petrou** [sangria-graphql/sangria#1280]
Hi 👋 

The v4.2.16 release seems to have broken binary compatibility due to https://github.com/sangria-graphql/sangria/pull/1268.

The main issue is that `sangria-derivation` inlines a call to this method (e.g., [here](https://github.com/sangria-graphql/sangria/blob/955a0c04c199946a5d060d497432f344084d5975/modules/derivation/src/main/scala-3/sangria/macros/derive/DeriveInputObjectTypeMacro.scala#L165)) so any derived `InputObjectType` that is stored in a separate JAR will throw a `NoSuchMethodError` error when updating Sangria to v4.2.16+

AFAICT you can avoid breaking binary compatibility by creating overloads of the old methods and proxy them to the new ones with `deprecationReason=None`. This way, code that was generated with versions prior up to v4.2.15 will be compatible with v4.2.16+

**Comment by yanns** [comment]
Thanks for the report. This should be fixed in https://github.com/sangria-graphql/sangria/releases/tag/v4.2.18
