### ISSUE TITLE
ambiguous implicit values in sangria 2.1.2

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#615]
New compilation error:

```
ambiguous implicit values:
[error]  both method outLookup in object GraphQLOutputTypeLookup of type [T](implicit out: sangria.schema.OutputType[T]): sangria.macros.derive.GraphQLOutputTypeLookup[T]
[error]  and method interfaceLookup in object GraphQLOutputTypeLookup of type [T](implicit interfaceType: sangria.schema.InterfaceType[_, T]): sangria.macros.derive.GraphQLOutputTypeLookup[T]
[error]  match expected type sangria.macros.derive.GraphQLOutputTypeLookup[MyClass]
```

**Comment by yanns** [comment]
Caused by https://github.com/sangria-graphql/sangria/pull/600
